### PR TITLE
Fixes for build errors

### PR DESCRIPTION
**Pull request by MiSimon**
With this fixes i can build it with the following commands (using Ubuntu 20.04 and installed gnu-efi with sudo apt install gnu-efi):
```
 gcc -I/usr/include/efi -I/usr/include/efi/x86_64 -fpic -ffreestanding -fno-stack-protector -fno-stack-check -fshort-wchar -mno-red-zone -maccumulate-outgoing-args -c main.c -o main.o
 ld -shared -Bsymbolic -L/usr/lib/ -Telf_x86_64_efi.lds /usr/lib/crt0-efi-x86_64.o main.o -o main.so -lgnuefi -lefi
 objcopy -j .text -j .sdata -j .data -j .dynamic -j .dynsym  -j .rel -j .rela -j .rel.* -j .rela.* -j .reloc --target efi-app-x86_64 --subsystem=10 main.so main.efi
```

### CODE REVIEW

**Comment by RapRaf** [comment]
it works! thank you so much

**Comment by RapRaf** [comment]
It doesn't work. It compiles but when executed in efi shell it doesn't send packets

**Comment by MiSimon** [comment]
Your efi shell should contain a "ping" command verify that this command works. If not there may be an option in your uefi setup that enables/disables the network stack.

**Comment by RapRaf** [comment]
Hello, I can ping from the efi shell and I can receive ping from another Pc shell..it’s just the application that doesn’t send.
I’m waiting the packet on an echo server and listening with wireshark but nothin comes out from the app

Raffaele.

**Comment by MiSimon** [comment]
I have successfully tested it again with your current main.c (just changed the local and remote addresses) on a system following uefi revision 2.6. What uefi revision are you using (enter the "ver" command in the uefi shell), there were some changes with revision 2.5 (the IP4Config2Protocol replaced the old IP4ConfigProtocol).

**Comment by RapRaf** [comment]
Thank you, when I go back from work I’ll let you know

Raffaele.

**Comment by RapRaf** [comment]
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (American Megatrends, 0x0005000D)

This is my ver

**Comment by MiSimon** [comment]
You can try to enable dhcp in the uefi shell and set Udp4ConfigData.UseDefaultAddress to TRUE and both Udp4ConfigData.StationAddress and Udp4ConfigData.SubnetMask to all zero, you can also try and set Udp4ConfigData.StationPort to 0. 
If any step fails it should print an error message if you enable the TRACE and LOG macros. 

Be aware that  dp4ConfigData.AcceptPromiscuous = TRUE can cause errors if a packet is received that is meant for another host.

**Comment by RapRaf** [comment]
When I come back from work I’m going to send you my main.c


Raffaele.

**Review by RapRaf — APPROVED** [review]

**Pull request closed without merging**
